"""init

Revision ID: 2367b0752c9b
Revises: 
Create Date: 2023-12-21 17:31:40.011444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2367b0752c9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('leiCode', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('leiCode')
    )
    op.create_table('osr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('leiCode', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('link_to_template', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('leiCode')
    )
    op.create_table('bids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('beginDate', sa.Date(), nullable=False),
    sa.Column('ONE_A', sa.Integer(), nullable=True),
    sa.Column('ONE_B', sa.Integer(), nullable=True),
    sa.Column('TWO_A', sa.Integer(), nullable=True),
    sa.Column('TWO_B', sa.Integer(), nullable=True),
    sa.Column('clientLeiCode', sa.String(length=50), nullable=False),
    sa.Column('osrName', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('osr_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['osr_id'], ['osr.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('beginDate', 'clientLeiCode', 'osrName', 'ONE_A', 'ONE_B', 'TWO_A', 'TWO_B', name='unique_bid'),
    sa.UniqueConstraint('beginDate', 'client_id', 'osr_id', name='unique_3')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bids')
    op.drop_table('osr')
    op.drop_table('client')
    # ### end Alembic commands ###
